Traceback (most recent call last):
  File "C:\Users\vc00004\Anaconda3\envs\pypo-env\lib\site-packages\jupyter_cache\executors\utils.py", line 58, in single_nb_execution
    executenb(
  File "C:\Users\vc00004\Anaconda3\envs\pypo-env\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\vc00004\Anaconda3\envs\pypo-env\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\vc00004\Anaconda3\envs\pypo-env\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\vc00004\Anaconda3\envs\pypo-env\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\vc00004\Anaconda3\envs\pypo-env\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\vc00004\Anaconda3\envs\pypo-env\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\vc00004\Anaconda3\envs\pypo-env\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
fDIS, fDOS, convergence = nlp_based_approach(DOS_bounds, 
                                             DOS_resolution,
                                             dma_mr_design, 
                                             u0,
                                             lb,
                                             ub,
                                             constr=(con),
                                             method='ipopt',
                                             plot=True,
                                             ad=True,
                                             warmstart=True)
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mAttributeError[0m                            Traceback (most recent call last)
Cell [1;32mIn[8], line 1[0m
[1;32m----> 1[0m fDIS, fDOS, convergence [38;5;241m=[39m [43mnlp_based_approach[49m[43m([49m[43mDOS_bounds[49m[43m,[49m[43m [49m
[0;32m      2[0m [43m                                             [49m[43mDOS_resolution[49m[43m,[49m
[0;32m      3[0m [43m                                             [49m[43mdma_mr_design[49m[43m,[49m[43m [49m
[0;32m      4[0m [43m                                             [49m[43mu0[49m[43m,[49m
[0;32m      5[0m [43m                                             [49m[43mlb[49m[43m,[49m
[0;32m      6[0m [43m                                             [49m[43mub[49m[43m,[49m
[0;32m      7[0m [43m                                             [49m[43mconstr[49m[38;5;241;43m=[39;49m[43m([49m[43mcon[49m[43m)[49m[43m,[49m
[0;32m      8[0m [43m                                             [49m[43mmethod[49m[38;5;241;43m=[39;49m[38;5;124;43m'[39;49m[38;5;124;43mipopt[39;49m[38;5;124;43m'[39;49m[43m,[49m
[0;32m      9[0m [43m                                             [49m[43mplot[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m
[0;32m     10[0m [43m                                             [49m[43mad[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m,[49m
[0;32m     11[0m [43m                                             [49m[43mwarmstart[49m[38;5;241;43m=[39;49m[38;5;28;43;01mTrue[39;49;00m[43m)[49m

File [1;32m~\Documents\python_operability\python_operability\src\pypo.py:929[0m, in [0;36mnlp_based_approach[1;34m(DOS_bounds, DOS_resolution, model, u0, lb, ub, constr, method, plot, ad, warmstart)[0m
[0;32m    926[0m ax [38;5;241m=[39m fig[38;5;241m.[39madd_subplot([38;5;241m1[39m,[38;5;241m2[39m,[38;5;241m1[39m)
[0;32m    927[0m [38;5;66;03m# plt.subplot(121)[39;00m
[1;32m--> 929[0m [43max[49m[38;5;241;43m.[39;49m[43mrcParams[49m[[38;5;124m'[39m[38;5;124mfigure.facecolor[39m[38;5;124m'[39m] [38;5;241m=[39m [38;5;124m'[39m[38;5;124mwhite[39m[38;5;124m'[39m
[0;32m    930[0m ax[38;5;241m.[39mscatter(fDIS[:, [38;5;241m0[39m], fDIS[:, [38;5;241m1[39m], s[38;5;241m=[39m[38;5;241m16[39m,
[0;32m    931[0m             c[38;5;241m=[39mnp[38;5;241m.[39msqrt(fDOS[:, [38;5;241m0[39m][38;5;241m*[39m[38;5;241m*[39m[38;5;241m1[39m [38;5;241m+[39m fDOS[:, [38;5;241m1[39m][38;5;241m*[39m[38;5;241m*[39m[38;5;241m1[39m),
[0;32m    932[0m             cmap[38;5;241m=[39mcmap, antialiased[38;5;241m=[39m[38;5;28;01mTrue[39;00m,
[0;32m    933[0m             lw[38;5;241m=[39mlineweight, marker[38;5;241m=[39m[38;5;124m'[39m[38;5;124ms[39m[38;5;124m'[39m,
[0;32m    934[0m             edgecolors[38;5;241m=[39medgecolors)
[0;32m    935[0m ax[38;5;241m.[39mset_ylabel([38;5;124m'[39m[38;5;124m$u_[39m[38;5;132;01m{2}[39;00m[38;5;124m$[39m[38;5;124m'[39m)

[1;31mAttributeError[0m: 'Axes' object has no attribute 'rcParams'
AttributeError: 'Axes' object has no attribute 'rcParams'

